About
-----
This is a crude hack of link:https://github.com/katmagic/Shallot[Shallot], a tool for
generating customized .onion hidden service address and the corresponding keys. My modifications
simply allow the tool generate a full 40 byte public key hash instead of the truncated hash
used for onion addresses. Once it has found an identity key digest matching the given
pattern it outputs the base32 encoded digest followed by the corrosponding private
key.

Note: I have a feeling this script has a bug and is not generating correct output everytime.
You should confirm the generated identiy_key from the private key by some other means such
as openssl.

	openssl rsa -in secret_id_key -pubout -outform DER | tail -c +23 | sha1sum | head -c 40 | python -c "import base64,sys; print base64.b32encode(sys.stdin.readline().strip('\n').decode('hex')).lower()"


Installation
------------
	$ ./configure && make
	$ ./id_key_gen

Usage
-----
	$ ./id_key_gen ^tor
	torvo2fumwgmhcxl3d4npjm7r444s5kp
	-----BEGIN RSA PRIVATE KEY-----
	MIICXQIBAAKBgQDnmBhm2Bv0QMGmV+EqAW87xNpv+dYKJ0TiJ35GdNI0KHGFq++B
	jp0hQagjXy9i7qOrnha6ykSokoSWxDyyVcPAB4fGa65WoWw5UisebGLzG+zNjSVs
	aumwSOTEWI/FgwmA38xy9CG2rx9J2qSvwZLNLaqInkbGLOH1WPJwyQib7wIDAcBb
	AoGAC8ZG3k+Zp8RWeNp4UDBKlyr3tB8d9jWsCE769GphNSgGGgi7Ox/YB2munTcX
	zUM/64EGbsMjnM2hlRhoTf+pNeFHaHR6AK8VvJMzOYFUBSiB7/P8g1T3Tc3MJaTo
	GBQedl3RB8r4Kc/lalVRuAz7ouZ9BiT9XoGJYihlE9sBSecCQQD+gmVfl00AXm/v
	cs4LqAVXG/A5teFAOBL6hvt7U5gEKYQHGrGeLMVnSmA4z+ePj1eURi6MOY2mHtYh
	cAjBSRnjAkEA6PNXRBJGYc3QmKio1DG1vOJ+0brt4OJZu+PlVjyFxWWSRscqg6Cy
	QRTH2ReF99f2NoAicqDSV5UCodwtaCWDhQJAFxL5g2o8NzDJXM+NECnAihNL4ZvL
	28nfLlpSsa7IeR7umjtm058Mw8ZKKIUY9h7bPJYLHKdG2hG5zSi4TxBfNwJBAI+v
	PaOLT6GAjiSl4eEIXl6P7WN6NdsVy03tkoi+vpSzxVeEL0ugxanvMZmM248ZbpQO
	eAok1qU7Umxef96p22MCQQCxEXN810vKjrXlDmXSDHLSBcJZMflrklVkg4PQGVm5
	hAwPyZAWxUUgjKRgS0aZ7O3JxUbFc5vuyMixn2N6VO3+
	-----END RSA PRIVATE KEY-----


If you place the RSA private key (including its header and footer) in a file
called `secret_id_key` in the `keys` directory of the `DataDir` you specified in your torrc, then when you restart
your Tor, it should be running with an indentity digest matching the one generated.
